### ISSUE TITLE
Using KLR for knock detection with aftermarket ECU

### ISSUE THREAD

**Issue by boxidau** [jhnbyrn/951-KLR-PAGES#1]
Hi! Firstly amazing work, loving the detailed analysis!

I think I know the answer to these questions based on your writings but I'll ask anyway. I'm running a megasquirt without any onboard knock filtering hardware, however it can take a logic input from an external knock module. I still have the KLR in my 951 however the KLR is not involved in the ignition timing at all, it's completely bypassed. The KLR is effectively just running the boost gauge on the dash.

I'd like to utilize the KLR if possible for it's knock detection capabilities, I'm actually very impressed at how advanced it was based on your reverse engineering efforts. I know it has a "knock/no knock" output on pin 15, however without the 11degree BTDC timing signal it seems unlikely that KLR can do anything at all. 

Q1 - without the timing signal is it safe to assume the KLR will not do any knock related activities
Q2 - do you think it would be possible (or even desirable) to modify the KLR to operate without this signal
Q3 - if a timing signal could be generated and provided would this be enough to get the KLR to operate the knock/no-knock signal

**Comment by jhnbyrn** [comment]
Thanks, I'm glad you found it helpful! It's certainly a niche area. 

1. Yes, that's correct. The trigger signal (as it's called in Porsche documentation) is absolutely essential. Without this, the KLR can't really do anything. I think it needs the ignition signal input to do knock detection too, because there's some variable rotation that happens in the INT routine iirc. 

2. No, I don't think that would be feasible. The trigger signal is used as a kind of pseudo external interrupt, and this is fundamental to the software architecture. Even if the software was redesigned, for knock detection the KLR *must* know the crank angle, because knocking only happens within a certain window ATDC.

3. Yes I think that would work if you supply the necessary signals from the DME to the KLR. You don't have to let the KLR control your timing. Once it has all the inputs it needs, it has no way of detecting if the timing is actually getting pulled or not. I'm not sure how your bypass was done, but you should make sure that the KLR is still getting the throttle position signal, because it does use that for knock detection. 

One thing I'm not sure of is whether the knock/no knock signal will meet the logic timing requirements for your MS setup. I haven't seen the trace, but from looking at the code it looks like the length of the pulse would be reduced at higher rpm. It might still work. I know that [Vitesse Racing has a knock monitor](http://www.vitesseracing.com/html/v-knock.html) that takes it's input from the KLR pin 15 and displays a visual indicator, and it can be configured to work with data loggers, so that would probably solve the problem, if there is one. 

It's also worth looking at the [J&S Safeguard](http://www.jandssafeguard.com/) - that's an aftermarket knock control system that was based on the 951 KLR. It might have more configurability for working with the MS system. 

I hope this helps.

**Comment by boxidau** [comment]
thanks @jhnbyrn 

generating the signals is possible but it's unlikely I can do it with the megasquirt directly as they don't publish their source which would need modification. I'd probably end up using an arduino running modified speeduino code or something similar to generate these signals. So while it's certainly possible, probably not worth it, when as you suggest an external knock detection system is probably easier.
